### ISSUE TITLE
SQS Messages getting split into 2

### ISSUE THREAD

**Issue by scottharris** [httpstergeek/splunk-sqs#3]
Just testing using your app to poll a sqs queue which is receiving auto scale events from a sns topic.

I terminated an instance in the asg which then got replace and in the sqs I received 2 messages, 1 for the termination and 1 for the launch of the new instance.  When the 2 messages are retrieved and indexed into splunk i end up with 4 events

Have attached an export of the 4 
[1454289629_1037362.txt](https://github.com/httpstergeek/splunk-sqs/files/111630/1454289629_1037362.txt)
splunk events

**Comment by scottharris** [comment]
I updated props.conf and added the following which has fixed the splitting
 KV_MODE = json
 LINE_BREAKER = "(^){"
 NO_BINARY_CHECK = 1
  SHOULD_LINEMERGE = false

**Comment by httpstergeek** [comment]
Not a bug as you can add props file or custom js handler for your data.
